### ISSUE TITLE
Installation on OSX is broken 

### ISSUE THREAD

**Issue by karstenw** [moyaproject/moya#5] opened 2015-06-28 18:51 UTC
moya neither compiles nor installs (sudo pip...) on OSX 10.6 and Python 2.7.9 (32-bit intel).

It breaks on installing 'pyinotify' which seem to be a Linux only package.

From the build log:
```
...
Requirement already satisfied (use --upgrade to upgrade): requests in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg (from moya)
Requirement already satisfied (use --upgrade to upgrade): lxml in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from moya)
Collecting colorama (from moya)
  Downloading colorama-0.3.3.tar.gz
Collecting premailer (from moya)
  Downloading premailer-2.9.2-py2-none-any.whl
Collecting pyinotify (from moya)
  Downloading pyinotify-0.9.6.tar.gz (60kB)
    100% |################################| 61kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    inotify is not available on macosx-10.4-i386
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-Hdm94F/pyinotify
```

**Comment by willmcgugan** [comment] 2015-06-29 08:29
I don't have a Mac here to test, but that dependency is non-essential, it speeds up auto-reload. I will make that conditional in the setup. Would you mind testing again once I have done that?

**Comment by karstenw** [comment] 2015-06-29 08:45
On 29.06.2015, at 10:29, Will McGugan wrote:

> I don't have a Mac here to test, but that dependency is non-essential, it speeds up auto-reload. I will make that conditional in the setup. Would you mind testing again once I have done that?

I'll do that.

**Comment by karstenw** [comment] 2015-08-16 14:18
builds and installs.

**Comment by willmcgugan** [comment] 2015-08-17 15:49
Awesome. Thanks.

**Comment by karstenw** [comment] 2015-08-17 16:25
Sorry, it's only one step further...

% moya -v
0.5.18a

% moya start project
?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
?                                                          Moya Project Wizard                                                        

...

Where should Moya write the project files?  ./testingmoya 

unknown encoding: 
Exit 255
%

**Comment by willmcgugan** [comment] 2015-08-17 17:17
The question marks are probably some encoding issue with the unicode borders. Not sure about that 'unknown encoding' error though.

Any chance you can run the project in "/example projects/blether"? 

moya db sync
moya auth#cmd.init
moya runserver

If that runs a server then it will be a very good sign.

I'm actually planning to get a Macbook, so I should be able to short these issues soon.

**Comment by karstenw** [comment] 2015-08-17 18:05
All commands end with that "unknown encoding:" line


On 17.08.2015, at 19:17, Will McGugan wrote:

> The question marks are probably some encoding issue with the unicode borders. Not sure about that 'unknown encoding' error though.
> 
> Any chance you can run the project in "/example projects/blether"? 
> 
> moya db sync
> moya auth#cmd.init
> moya runserver
> 
> If that runs a server then it will be a very good sign.

Unfortunately not.

-karsten

**Comment by willmcgugan** [comment] 2015-09-06 15:42
Hi,

I have a Mac Book to develop on now, and I believe I've fixed the Mac issues. Although I was never able to reproduce the encoding error. Would you mind testing? 0.5.18 can be installed from PIP, or the latest version from Github if you prefer.

**Comment by karstenw** [comment] 2015-09-06 20:01
I started debugging this (the linenumbers don't match the source since it's sprinkled with 'pdb.set_trace()):

```python
> /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moya-0.5.21a1-py2.7.egg/moya/command/sub/templatebuilder.py(41)write_file()
-> with fs.open(filename, 'wt') as f:
(Pdb) pp locals()
{'file_lines': [u'# encoding=UTF-8',
                u'from __future__ import unicode_literals',
                u'from moya.wsgi import Application',
                u'',
                u"application = Application('./', ['local.ini', 'production.ini'], server='main', logging='prodlogging.ini')"],
 'file_type': u'TEXT',
 'filename': u'/wsgi.py',
 'fs': MemoryFS()}
(Pdb) l
 36  	    file_lines = []
 37  	
 38  	    def write_file(filename, file_type):
 39  	        if filename:
 40  	            if file_type.lower() == "text":
 41  ->	                with fs.open(filename, 'wt') as f:
 42  	                    f.write('\n'.join(file_lines) + '\n')
 43  	            elif file_type.lower() == "wraptext":
 44  	                import textwrap
 45  	                with fs.open(filename, 'wt') as f:
 46  	                    for line in file_lines:
(Pdb) n
LookupError: 'unknown encoding: '
> /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moya-0.5.21a1-py2.7.egg/moya/command/sub/templatebuilder.py(41)write_file()
-> with fs.open(filename, 'wt') as f:
(Pdb) p filename
u'/wsgi.py'
```

**Comment by willmcgugan** [comment] 2015-09-06 20:44
I'm a bit puzzled by that error. Could you tell me what this code outputs?

    import locale
    print(locale.getpreferredencoding())

**Comment by karstenw** [comment] 2015-09-06 21:19
```python
>>> print(locale.getpreferredencoding())

>>> 
```

**Comment by willmcgugan** [comment] 2015-09-07 09:05
That's interesting. I get 'UTF-8'. I may have a fix for that.

**Comment by willmcgugan** [comment] 2015-09-07 15:55
I think the fix may have been in the fs module. Can you try the following:

    pip install fs --upgrade

You should get fs 0.5.3

If that doesn't fix it, I will try and figure out why Python is reporting a locale on your system. I don't know enough about Macs to comment.

**Comment by karstenw** [comment] 2015-09-07 16:23
It worked.

moya start project

now completes.

```shell
% moya db sync
unknown encoding: 
Exit 255
```

**Comment by willmcgugan** [comment] 2015-09-07 16:29
Any extra info with this?

    moya --debug db sync

**Comment by willmcgugan** [comment] 2015-09-07 17:37
Did some Googling on this. I think the following will fix it (from the terminal):

    export PYTHONIOENCODING=utf-8

That's obviously not ideal. I need to have a think about what a more permanent fix should be.

**Comment by karstenw** [comment] 2015-09-07 18:58
On 07.09.2015, at 19:37, Will McGugan wrote:

> Did some Googling on this. I think the following will fix it (from the terminal):
> 
>    export PYTHONIOENCODING=utf-8
> 
> That's obviously not ideal. I need to have a think about what a more permanent fix should be.

I use the unicode-sandwich(tm) http://nedbatchelder.com/text/unipain/unipain.html

I'll try it later.

**Comment by karstenw** [comment] 2015-09-07 21:07
I'm using tcsh, so setenv.

```shell
% setenv PYTHONIOENCODING "utf-8"
% moya --debug db sync
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moya-0.5.22a1-py2.7.egg/moya/command/app.py", line 193, in run
    return subcommand.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moya-0.5.22a1-py2.7.egg/moya/command/sub/db.py", line 40, in run
    getattr(self, "sub_" + self.args.dbsubcommand)()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moya-0.5.22a1-py2.7.egg/moya/command/sub/db.py", line 43, in sub_sync
    application = WSGIApplication(self.location, self.get_settings(), validate_db=True, disable_autoreload=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moya-0.5.22a1-py2.7.egg/moya/wsgi.py", line 188, in __init__
    self.build(breakpoint=breakpoint_startup, strict=strict)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moya-0.5.22a1-py2.7.egg/moya/wsgi.py", line 226, in build
    master_settings=self.master_settings)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moya-0.5.22a1-py2.7.egg/moya/build.py", line 188, in build_server
    master_settings=master_settings)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moya-0.5.22a1-py2.7.egg/moya/build.py", line 66, in build
    archive.cfg = SettingsContainer.read(fs, settings_path, master=master_settings)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moya-0.5.22a1-py2.7.egg/moya/settings.py", line 61, in read
    with fs.open(path, 'rt') as settings_file:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fs/osfs/__init__.py", line 232, in open
    return io.open(sys_path, mode=mode, buffering=buffering, encoding=encoding, errors=errors, newline=newline)
LookupError: unknown encoding: 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Exit 255
% 
```

**Comment by willmcgugan** [comment] 2015-09-08 13:41
That suggests to me that your Python environment is broken somehow.

Could you create a text file called 'test.txt' and try reading it with the following:

    import io
    with io.open('test.txt') as f:
        print(f.read())

If that breaks, then it's an issue with your environment. Possibly because you are using tcsh.

**Comment by karstenw** [comment] 2015-09-08 14:34
```python
import io
with io.open('test.txt') as f:
    print(f.read())
```

That breaks. I don't remember if it was intentional or not nor which parameter was affected.

Checking my env vars I see that only LC_MESSAGES is set to "en_US.UTF-8". I remember doing that because a german speaking git freaked me out. You really don' want that.

Setting LC_ALL to "en_US.UTF-8" makes the code run.

```shell
% moya db sync
[========================] 100% sync complete                                          
╭────────────────────────────────────────────────┬────────╮
│ app                                            │ synced │
├────────────────────────────────────────────────┼────────┤
│ <application site.testing-moya:site>           │        │
│ <application moya.forms:forms>                 │        │
│ <application moya.widgets:widgets>             │        │
│ <application moya.auth:auth>                   │ 8      │
│ <application moya.session:session>             │ 1      │
│ <application moya.signup:signup>               │ 1      │
│ <application moya.admin:admin>                 │        │
│ <application moya.static:media>                │        │
│ <application moya.debug:debug>                 │ 1      │
│ <application moya.twitter.bootstrap:bootstrap> │        │
│ <application moya.welcome:welcome>             │        │
│ <application moya.links:links>                 │        │
│ <application moya.favicon:favicon>             │        │
│ <application moya.comments:comments>           │ 4      │
│ <application moya.pages:pages>                 │ 1      │
│ <application moya.blog:blog>                   │ 1      │
│ <application moya.feedback:feedback>           │        │
│ <application moya.jsonrpc:jsonrpc>             │        │
│ <application moya.wysihtml5:wysihtml5>         │        │
│ <application moya.google.recaptcha:recaptcha>  │        │
╰────────────────────────────────────────────────┴────────╯
```

For now I have added the LC_ALL var to my env and will see how that works out. Normally I prefer that my scripts crash when assuming too much about encoding. OSX unicode filenames with non-ascii codepoints can be a real pita due to unicode normalisation.

**Comment by willmcgugan** [comment] 2015-09-08 18:58
Glad we got to the bottom of that. It doesn't look like there is much I can do about that from the Moya side. At least we know it installs, so I'll close this ticket.

**Closed by willmcgugan** 2015-09-08 18:58 UTC
